application:
  port: 8080

adyen:
#api_key: $APP_ADYEN__API_KEY
#merchant_account_name: $APP_ADYEN__MERCHANT_ACCOUNT_NAME

auth0:
#authority: $APP_ADYEN__AUTHORITY
#audience: $APP_ADYEN__AUDIENCE
#domain: $APP_ADYEN__DOMAIN
#client_origin_url: $APP_ADYEN__CLIENT_ORIGIN_URL

database:
  port: 5432
  host: localhost
  database_name: router
  #username: $APP_DATABASE__USERNAME
  #password: $APP_DATABASE__USERNAME

footprint:
#api_key: $APP_FOOTPRINT__API_KEY

lithic:
  mode: "sandbox"
  #api_key: $APP_LITHIC__API_KEY

otel:
  otlp_headers: "x-honeycomb-team=***REMOVED***"
  otlp_endpoint: "https://api.honeycomb.io:443"
  service_name: "test"

redis:
  url: "redis://localhost"
  port: 6379


